### ISSUE TITLE
Which parameters can I change to increase my detected keypoints?

### ISSUE THREAD

**Issue by brspurri** [pablofdezalc/akaze#18]
Hi there,

Which parameters would I change if I want to increase the number of my keypoints? I realize, that in doing so, I will likely decrease sensitivity, but I'm willing to experiment with that.

It seems that the average of my images (`500px` x `500px`) yield around `~200` to `~300` keypoints. I'm looking to see if my matching gets better if I'm able to get this number up to `~1000`.

Any pointers?

Cheers,
Brett

**Comment by pmoulon** [comment]
Hi,
Just change the value for the threshold:
=> default value dthreshold = 0.001f;
Possible range [0.001f; 0.00001f]

The easiest way to test is to divide per 10 or 100 the threshold and look to your match.

Regards,
Pierre

**Comment by brspurri** [comment]
Ok, great. Is that typically the only parameter? Or are there others I can modify. I'll re-read Pablo's paper and report back if I find anything. For now, I'll close the issue though. Thanks for your help!
