### ISSUE TITLE
Finding scale space extrema

### ISSUE THREAD

**Issue by nbergst** [pablofdezalc/akaze#24]
Hi,

I'm curious about the lines 333-334 and 338-339 in AKAZE.cpp. The addition + .5*(ratio-1.0) to the accepted points are compared with incoming points that do not have that extra term added to them. Is this intentional? I'm curious since I'm working on a GPU version (with Mårten Björkman who has previously posted here, and Alessandro Pieropan). The idea is that the GPU version should produce the same results as the CPU version, which imposes constraints on the extrema detection and filtering which are hard to do in parallel. In particular the lines mentioned above are giving me trouble when performing the filtering in parallel.

The GPU version can of course be made more efficient if a different result compared to the CPU version can be accepted, but I figured it might be worth having an identical version as well.

Niklas

**Comment by pablofdezalc** [comment]
Hi Niklas,

That seems to be a bug in the code although I suspect it will not change much the performance. The distance computation in line 301 should also consider the factor .5*(ratio-1.0). 

I would say that if your GPU version produces almost similar performance as the original version with different constraints in the extrema detection that will be good.

Regards

**Comment by nbergst** [comment]
Hi Pablo,

Thanks for the quick reply! Even if not considering the issue, the detected keypoint set will be very similar to the CPU code. I agree that that is enough, and that even getting similar performance is enough. We might provide two versions where one is more aimed at performance and one at getting the same keypoints as the CPU version. I will let you know when the code is ready. We get quite the speedup compared to the CPU version, so I hope people will find it useful.

Niklas
