### ISSUE TITLE
Error compiling akaze.mexa64

### ISSUE THREAD

**Issue by Tariq-Abuhashim** [pablofdezalc/akaze#25]
Warning: You are using gcc version '4.8.4'. The version of gcc is not supported. The version
currently supported with MEX is '4.7.x'. For a list of currently supported compilers see:
http://www.mathworks.com/support/compilers/current_release. 

I am also using OpenCV- 2.4.8 on ubuntu.

I run the following in the /akaze/mex folder:
mex('akaze.cpp','-I../src/lib/','-L../build/lib/','-lAKAZE','-L/usr/local/lib/',...
    '-lopencv_imgproc','-lopencv_core','-lopencv_calib3d','-lopencv_highgui','-lgomp');

The error message:
Error using mex
~/Dev/akaze/mex/akaze.cpp: In function ‘void mexFunction(int, mxArray**, int, const mxArray**)’:
~/Dev/akaze/mex/akaze.cpp:218:2: error: ‘AKAZE’ was not declared in this scope
  AKAZE evolution(options);
  ^
......./akaze/mex/akaze.cpp:218:2: note: suggested alternatives:
In file included from /usr/local/include/opencv2/features2d/features2d.hpp:48:0,
                 from ~/Dev/akaze/mex/../src/lib/utils.h:12,
                 from ~/Dev/akaze/mex/../src/lib/AKAZE.h:14,
                 from ~/Dev/akaze/mex/akaze.cpp:22:
/usr/local/include/opencv2/features2d.hpp:643:20: note:   ‘cv::AKAZE’
 class CV_EXPORTS_W AKAZE : public Feature2D
                    ^
In file included from ~/Dev/akaze/mex/akaze.cpp:22:0:
~/Dev/akaze/mex/../src/lib/AKAZE.h:23:9: note:   ‘libAKAZE::AKAZE’
   class AKAZE {
         ^
~/Dev/akaze/mex/akaze.cpp:218:8: error: expected ‘;’ before ‘evolution’
  AKAZE evolution(options);
        ^
~/Dev/akaze/mex/akaze.cpp:219:2: error: ‘evolution’ was not declared in this scope
  evolution.Create_Nonlinear_Scale_Space(img_32);
  ^

Error in make (line 9)
mex('akaze.cpp','-I../src/lib/','-L../build/lib/','-lAKAZE','-L/usr/local/lib/',...

**Comment by ljlijie** [comment]
AKAZE is defined in the namespace libAKAZE as indicated in the error.

So you might want to use the name space in the cpp, or you can replace AKAZE by libAKAZE::AKAZE.
