### ISSUE TITLE
Which descriptor type should I use?

### ISSUE THREAD

**Issue by LingyuMa** [pablofdezalc/akaze#26]
Can someone explains the difference between Descriptor Type, 0-> SURF_UPRIGHT, 1->SURF 2-> M-SURF_UPRIGHT, 3->M-SURF 4-> M-LDB_UPRIGHT, 5->M-LDB

**Comment by pmoulon** [comment]
UPRIGHT (does not consider the rotation)

MLDB is the binary descriptor (see the paper)
MSURF is also describer in the paper.

**Comment by LingyuMa** [comment]
thanks!
