### ISSUE TITLE
Question: Scharr derivatives in AKAZE

### ISSUE THREAD

**Issue by hrnr** [pablofdezalc/akaze#32]
Hi Pablo,

I'm working on performance improvements of OpenCV version of your code. Thanks a lot your code, it is nicely readable. I have a few questions however:

1) Why does the Scharr needs to be computed twice? First [here](https://github.com/pablofdezalc/akaze/blob/master/src/lib/AKAZE.cpp#L140) for computing diffusivity and then for computing Hessian determinant [here](https://github.com/pablofdezalc/akaze/blob/master/src/lib/AKAZE.cpp#L205). First is standard 3x3 Scharr, the second is using sigma-sized kernels. Would it be possible to compute it just once (either using sigma-sized or 3x3 kernel)?

2) Would it be possible to use only standard 3x3 Scharr for computing Hessian Determinant? There is a huge possible speedup.

3) Before processing the image is converted to floats. Could some parts use just bytes, without affecting accuracy too much?

Have a nice day.

Cheers,
Jiri

**Comment by pablofdezalc** [comment]
Hi Jiri,

**Why does the Scharr needs to be computed twice? First here for computing diffusivity and then for computing Hessian determinant here. First is standard 3x3 Scharr, the second is using sigma-sized kernels. Would it be possible to compute it just once (either using sigma-sized or 3x3 kernel)?**
The first computation is to get a regularized version of the gradient so we can compute the diffusivity function. The rest of computations are to compute the multiscale derivatives with increasing size with respect to scale. Perhaps here you can approximate some of the kernels with the first Scharr filter. 

**Would it be possible to use only standard 3x3 Scharr for computing Hessian Determinant? There is a huge possible speedup.**
As I mentioned above perhaps it is possible. I think the correct way to do it is the way I did, but if performance does not suffer you may get big speed ups by using just the standard 3x3 Scharr kernel.

**Before processing the image is converted to floats. Could some parts use just bytes, without affecting accuracy too much?**
I believe some pre-processing functions can be done with unsigned char or int. I have not explored much these options. 

Regards,
Pablo

**Comment by hrnr** [comment]
Thanks a lot for your insights.

I just quickly tried to used 3x3 Scharr for computing multiscale derivatives, but that does not play very well with finding scale space extrema, which runs much longer and probably is broken.

I'll keep you updated, if I achive anything interesting.

Have a nice weekend.

**Comment by hrnr** [comment]
ups, I kinda forget a bit about this issue. Thanks much for the feedback, AKAZE in OpenCV is now 2.2x - 3.77x faster. Reworking finding of scale space extremas with more efficient approach helped a lot when there is a lot of features detected.

https://github.com/opencv/opencv/pull/9444
