### ISSUE TITLE
Use Compute_Descriptors on an existing vector<KeyPoint>?

### ISSUE THREAD

**Issue by antithing** [pablofdezalc/akaze#33]
Hi, and thank you for making this code available. I am trying to split out the `Compute_Descriptors` function from the rest, so that i can use it on existing Keys, found in another function. (using this code also).
I get keypoints and descriptors. Then I filter out some of the keypoints, and now i want to find descriptors of the remaining Keypoints.  I have this function:

```
void Akaze::DetectDesciptorsOnly( cv::Mat &returnDesc, vector<cv::KeyPoint> Keys)
{
	//set up 
	if (bFirstLoopDescrip == false)
	{
		evolutionDescrip = new AKAZE(optionsDescrip);
		bFirstLoopDescrip = true;
	}
	cv::Mat desc;
	evolutionDescrip->Compute_Descriptors(Keys, desc);
	std::cout << "des " << desc.rows << std::endl;
	desc.copyTo(returnDesc);
}

```
But it always returns zero. The keypoint array has around 900 points going in. Where am i going wrong here? thanks!

**Comment by pablofdezalc** [comment]
Hi, 

In A-KAZE the descriptor is really attached to the detector. For being able to compute the descriptor you need to compute (or re-use the computations from the detector) the scale space. If you want to use a different detector and the descriptors from A-KAZE, you need to provide a way so that A-KAZE descriptors can be extracted from the scale space defined in the other detectors. 

Regards,
Pablo

**Comment by antithing** [comment]
Ah I see. So if I was to:

`AKAZE* evolutionDescrip;`

//detect with `evolutionDescrip` in one function

`evolutionDescrip->Compute_Descriptors(Keys, desc);`

in another function, that would work? 

Same instance of AKAZE, but in a different function.

thank you for your time.

**Comment by pablofdezalc** [comment]
It will work as long as you call Create_Nonlinear_Scale_Space(). However, keep in mind that when you use another detector in combination with A-KAZE descriptors you need to adapt the scale of the detected keypoints to an appropriate value for the descriptor computation.

**Comment by antithing** [comment]
Thank you. I have it working.
